spring:
  cloud:
    config:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost/marvel_db
    username: root
    password: Mysql561887!
    driver-class-name: com.mysql.cj.jdbc.Driver
data-access:
  marvel-url: https://gateway.marvel.com:443/v1/public/
config:
  marvel-api:
    ts: 1
    publickey: 0b9b6e3ac13acf77e0c80aa839c80409
    privatekey: 983303b5919e783c6cd2ab651b2a1e3e3a2a66e2
    limit: 100
    